### ISSUE TITLE
New release to PyPI

### ISSUE THREAD

**Issue by jaraco** [dsoprea/RijndaelPbkdf#4]
Thanks for accepting #3. We've been using that code with success for some time now. How about publishing it to PyPI?

**Comment by jaraco** [comment]
I'm happy to help with packaging releases (even configuring automated releases of tagged releases via Travis-CI) if that's helpful. Just make me maintainer on this repo and in PyPI.

**Comment by jaraco** [comment]
Alternatively, if you wish to maintain custody but still have automated releases, let me know and I'll send a PR with instructions on getting it configured.

**Comment by jaraco** [comment]
Aah. Sorry to [repeat myself](https://github.com/dsoprea/RijndaelPbkdf/issues/2#issuecomment-331516977). I thought I'd made this request, but I didn't see it until just now.

**Comment by Jeeppler** [comment]
Yes, please create a release with the fixes from @jaraco

**Comment by jaraco** [comment]
I've published a release from my fork, [pprp-bis](https://pypi.org/project/pprp-bis). Please use that instead.

**Comment by dsoprea** [comment]
I've pushed a new version: https://pypi.python.org/pypi/pprp/0.2.6

I just needed a gentle reminder.

**Comment by jaraco** [comment]
That's awesome. I've deleted pprp-bis. Thanks Dustin!

**Comment by dsoprea** [comment]
Thanks for the reminder. Sorry for the delay, again.



Dustin
